# What we study 
* scalers 
* vectors 
* matrices
* Dot product
* Matrix product

# Why we study this in AI ? :

* we do a lot of calculations
* so far, we deal with a lot of data. mostly data of the operations that we did , are based on linear algebra?
* lists and arrays are most important things.
* linear structures
* pandas 
* how to manipulate datas to get better output


columns = vectors

In [1]:
vector1 = [3,4,10]

vector2 = [2,4,10]

len(vector1)

3

In [5]:
matrix = [vector1,vector2]

matrix[1]

[2, 4, 10]

In [ ]:
matrix[1][0]     #slicing for list only accept 'integers'

2

In [ ]:
list1 = [1,2,3 'amin', [2,4,5], 6]

In [9]:
import numpy as np

arr = np.array(vector1)
arr

array([ 3,  4, 10])

In [11]:
arr.mean().round(2)

np.float64(5.67)

In [21]:
vector1 = [3,4,10]
vector2 = [2,5,20]
vector3 = [1,7,30]

matrix = [vector1,vector2,vector3]
matrix


[[3, 4, 10], [2, 5, 20], [1, 7, 30]]

In [22]:
matrixarr = np.array(matrix)

In [23]:
print(type(matrix))
print(type(matrixarr))

<class 'list'>
<class 'numpy.ndarray'>


In [40]:
print(matrixarr)
print()
matrixarr[0:3,0:2]

[[ 3  4 10]
 [ 2  5 20]
 [ 1  7 30]]



array([[3, 4],
       [2, 5],
       [1, 7]])

In [ ]:
matrixarr * 2 # this is the scalar multiplacation    #broadcasting
                # scaler operations with arrays
matrixarr.ndim
matrixarr.shape

(3, 3)

In [46]:
a = np.array([[1,3,5,7],
             [2,8,4,9]])
b = np.array([10,10,10,10])

a * b

array([[10, 30, 50, 70],
       [20, 80, 40, 90]])

In [ ]:
a = np.array([[1,3,5,7],
             [2,8,4,9]])
b = np.array([[10], [100]]) #another method that very nice actually

a + b

array([[ 11,  13,  15,  17],
       [102, 108, 104, 109]])

In [48]:
variance = np.array([14535,423542,24355,3523456])

n = np.array([145,542,355,3456])

((variance)**00.5) .round(2)

array([ 120.56,  650.8 ,  156.06, 1877.09])

In [50]:
covariance = np.array([14535,423542,24355,3523456])

n = np.array([145,542,355,3456])

stdx , stdy = np.array([381.22, 650.8])

r = covariance/(stdx * stdy)
r

array([ 0.05858573,  1.70715621,  0.09816686, 14.20187321])

In [55]:
x = np.array([[1,4,1],
             [2,5,2]])

w = np.array([10,10,10])
w2 = np.array([[10,2,3],
              [10,2,3],
              [10,2,3]])

# matrix multiplication x and w 

matmulxw = np.dot(x,w)
matmulxw

array([60, 90])

In [56]:
matmulxw2 = np.dot(x,w2)
matmulxw2

array([[60, 12, 18],
       [90, 18, 27]])

In [58]:
matmulxw2 = x @ w2
matmulxw2

array([[60, 12, 18],
       [90, 18, 27]])