In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np


In [3]:
np.__version__


'2.3.5'

when ever we are using . notation, dot notation, we aare trying to access the methods within a class

In [8]:
python_list = [1,2,3,'string',6.7]
numslist = [x for x in range(10)]
print(numslist)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [5]:
print(arr1*3)
print(type.arr1)

[ 3  6  9 12 15]


AttributeError: type object 'type' has no attribute 'arr1'

In [11]:
arr1D = np.array([1, 2, 3])
print(arr1D)

[1 2 3]


In [12]:
arr2D = np.array([[1, 2, 3],
[1, 2, 3]])
arr2D

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
#. ndim works on object and check their dimension
arr1D.ndim
print(f'dimension are: {arr1D.ndim}')

dimension are: 1


In [ ]:
print(f'Shape is: {np.shape(arr1D)}')
print(f'Shape is: {np.shape(arr2D)}')

Shape is: (3,)
Shape is: (2, 3)


In [ ]:
arr3D = np.array([[[1, 2, 3],[33, 55, 76]],
                  [[4, 5, 6],[7, 8, 9]],
                  [[11, 22, 33],[44, 18, 39]]])    ### nk gmbrkan .shape kna bygkan kek

print(arr3D.ndim)
print(arr3D.shape)    #output = (3,2,3): depth, row , column
print(arr3D[2,1,2])   #output = 39 sbb kita nk cri benda ikut koordinat index:1st row adalah 0 [baris ke 3, kotak ke 2,column ke 3]

3
(3, 2, 3)
39


In [15]:
arrayt = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arrayt = array.reshape(2, 6)
arrayt = array.reshape(3, 4)
# array = array.reshape(4, 4) # Too many elements
# array = array.reshape(2, 4) # Too few elements
arrayt = array.reshape(4, 3)
arrayt = array.reshape(2, 2, 3) # 3D


arrayt



array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
#How large array is, how many elements there are in array
size1D = arr1D.size
size1D


3

In [ ]:
size2D = arr2D.size
size2D

6

* int 8
* int 16
* int 32
* int 64

In [ ]:
type(arr1D)

numpy.ndarray

In [ ]:
#Broadcasting
arr1D * 10

array([10, 20, 30])

In [ ]:
arr1D + arr1D

array([2, 4, 6])

In [ ]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

arr2 = np.array([10,20,30,40,50])
print(arr2)

print('result :',arr1 * arr2)

[1 2 3 4 5]
[10 20 30 40 50]
result : [ 10  40  90 160 250]


In [ ]:
arr1 = np.array([1,2,3,])   ##Mmg akan jdi error sbb xdk 5 item array
print(arr1)

arr2 = np.array([10,20,30,40,50])
print(arr2)

print('result :',arr1 * arr2)

[1 2 3]
[10 20 30 40 50]


ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [ ]:
#Slicing & reshaping

#only list comprehensive we have used 

nums = [x for x in range(0,101,2)]
print(nums)

print(nums.type)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


AttributeError: 'list' object has no attribute 'type'

In [ ]:
nums1 =nums[3] 
print(nums1)

nums1 =nums[5] 
print(nums1)

nums1 =nums[8] 
print(nums1)

6
10
16


In [ ]:
nums1 = nums[100:0:-1]   #accessing elements in list

arraynums =np.array(nums)
print(arraynums)

print(arraynums[::-1])

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2   0]


In [ ]:
line = np.linspace(0,1,10)   #values are evenly spaced and stored in array
line

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

activity  🎇🎆🎁

#[0, 0.1, 0.2, 0.3, 0.4, 0.5]

In [41]:
line = np.linspace(0,1,10)
line = np.round(line,decimals=1)
print(line)

[0.  0.1 0.2 0.3 0.4 0.6 0.7 0.8 0.9 1. ]


In [ ]:
np.zeros((3,3))
np.ones((4,3))

## take of tuples of shape, return arrays

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#Random class in numpy
#numbers 
np.random.seed(40)

#randomarray= np.random.rand(3,4)
#randomarray

randomarray = np.random.randint(0,100,(3,3))  #  start, stop, (shape)
randomarray

array([[70, 91,  7],
       [37, 56, 50],
       [65, 12, 71]], dtype=int32)

In [ ]:
np.random.seed(40)

randomarray = np.random.randint(0,100,(3,3))  #  start, stop, (shape)
randomarray

array([[70, 91,  7],
       [37, 56, 50],
       [65, 12, 71]], dtype=int32)

Change and reshape
* transform, linear algebra

In [ ]:
randomarray = np.random.randint(0,100,(3,4))  #  start, stop, (shape)   #ubah jdi 1 dimensi
randomarray
print(randomarray)

print(randomarray.sum(axis=0))    #dia tambah untuk vertical  >>>>>>>>
print(randomarray.sum(axis=1))   #dia tambah untuk horizontal ^^^^^^^^

[[57 83 85 36]
 [63 74 88  0]
 [ 1 33 52 72]]
[121 190 225 108]
[261 225 158]


In [ ]:
flatarray = randomarray.flatten()   #Ubah jdi 2 dimensi
print(flatarray)

reshapedarray = flatarray.reshape(6,2)   #Ubah jdi 3 dimensi
print(reshapedarray)

[19 31 74 55 83 59 91 73 96 49 53 73]
[[19 31]
 [74 55]
 [83 59]
 [91 73]
 [96 49]
 [53 73]]


In [ ]:
#Transform
reshapedarray.T

array([[19, 74, 83, 91, 96, 53],
       [31, 55, 59, 73, 49, 73]], dtype=int32)

In [ ]:
#aggregations

data = np.array([85,94,22,68,94,54,98])

#sum
#mean
#min max

print(data.sum())
print(data.min())
print(data.max())

#Create a list of 1 to 10
#use list comprehension
#give me the addition of numbers from 1 to 10
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data.sum())

515
22
98
55


In [ ]:
nums = [x for x in range(0,11,1)]
print(nums)




[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
total = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(total.sum())

55


In [ ]:
###Solution by Trainer
array_amin= np.array([num for num in range(1,11)])
sum_of_array_amin = array_amin.sum()
print(sum_of_array_amin)
print(array_amin.mean())

55
5.5


splitting numpy arrays 🍔🍔🍔

In [ ]:


range_of_number = np.arange(1,11)
range_of_number.reshape(5,2)
print(range_of_number)

#exactly same as this
range_example =np.arange(1,101).reshape(50,2)
print(range_example)

#x input -----> y output
#1 -----> 2
#row are 50

[ 1  2  3  4  5  6  7  8  9 10]
[[  1   2]
 [  3   4]
 [  5   6]
 [  7   8]
 [  9  10]
 [ 11  12]
 [ 13  14]
 [ 15  16]
 [ 17  18]
 [ 19  20]
 [ 21  22]
 [ 23  24]
 [ 25  26]
 [ 27  28]
 [ 29  30]
 [ 31  32]
 [ 33  34]
 [ 35  36]
 [ 37  38]
 [ 39  40]
 [ 41  42]
 [ 43  44]
 [ 45  46]
 [ 47  48]
 [ 49  50]
 [ 51  52]
 [ 53  54]
 [ 55  56]
 [ 57  58]
 [ 59  60]
 [ 61  62]
 [ 63  64]
 [ 65  66]
 [ 67  68]
 [ 69  70]
 [ 71  72]
 [ 73  74]
 [ 75  76]
 [ 77  78]
 [ 79  80]
 [ 81  82]
 [ 83  84]
 [ 85  86]
 [ 87  88]
 [ 89  90]
 [ 91  92]
 [ 93  94]
 [ 95  96]
 [ 97  98]
 [ 99 100]]


In [ ]:
train_dataset = range_example[:10]
print(train_dataset)
test_dataset = range_example[40:]
print(test_dataset)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[[ 81  82]
 [ 83  84]
 [ 85  86]
 [ 87  88]
 [ 89  90]
 [ 91  92]
 [ 93  94]
 [ 95  96]
 [ 97  98]
 [ 99 100]]


In [ ]:
array_2d_matrix = np.ones((3,5))

print(array_2d_matrix)

print(array_2d_matrix.sum(axis=0))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[3. 3. 3. 3. 3.]
