In [1]:
pip install torch


   ---------------------------------------- 0.0/110.9 MB ? eta -:--:--
   - -------------------------------------- 3.9/110.9 MB 20.5 MB/s eta 0:00:06
   ----- ---------------------------------- 15.2/110.9 MB 39.5 MB/s eta 0:00:03
   ------------- -------------------------- 37.0/110.9 MB 61.6 MB/s eta 0:00:02
   --------------------- ------------------ 59.8/110.9 MB 74.5 MB/s eta 0:00:01
   -------------------------- ------------- 73.4/110.9 MB 73.6 MB/s eta 0:00:01
   ------------------------------ --------- 85.5/110.9 MB 71.1 MB/s eta 0:00:01
   --------------------------------------  109.1/110.9 MB 77.5 MB/s eta 0:00:01
   ---------------------------------------- 110.9/110.9 MB 71.0 MB/s  0:00:01
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 70.9 MB/s  0:00:00
   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   ---------------------------------------- 6.3/6.3 MB 91.0 MB/s  0:00:00
   ---

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import torch

#check if GPU is avaiable
print('Is CUDA (GPU) available?', torch.cuda.is_available())

Is CUDA (GPU) available? False


In [14]:
device = 'CUDA' if torch.cuda.is_available() else 'cpu'

In [5]:
t_scaler = torch.tensor(5)

In [6]:
#1 D  tensor

t_1D = torch.tensor([1,2,3,4])
t_1D.shape

torch.Size([4])

In [7]:
#2 D  tensor

t_2D = torch.tensor([[1,2,3,4],
                     [1,2,3,4],
                     [1,2,3,4]])
t_2D.shape

torch.Size([3, 4])

In [8]:
# 

t_3D = torch.tensor([
                    [[1,2,3,4],[1,2,3,4]],
                    [[1,2,3,4],[1,2,3,4]],
                    [[1,2,3,4],[1,2,3,4]]
                    ])
t_3D.shape

torch.Size([3, 2, 4])

In [9]:
# Broadcasting works here

t_3D * 2

tensor([[[2, 4, 6, 8],
         [2, 4, 6, 8]],

        [[2, 4, 6, 8],
         [2, 4, 6, 8]],

        [[2, 4, 6, 8],
         [2, 4, 6, 8]]])

In [10]:
gen_ten = torch.rand(1,)
gen_ten

tensor([0.8686])

In [11]:
gen_ten = torch.rand(1,5)
gen_ten

tensor([[0.3692, 0.5478, 0.6244, 0.1794, 0.6044]])

In [13]:
gen_ten = torch.rand(2,5,3)
gen_ten

tensor([[[0.7928, 0.7602, 0.0157],
         [0.2462, 0.2352, 0.9650],
         [0.5689, 0.5566, 0.0591],
         [0.9205, 0.8876, 0.6231],
         [0.0816, 0.8773, 0.1217]],

        [[0.3261, 0.6545, 0.7424],
         [0.6009, 0.4839, 0.5381],
         [0.5190, 0.2589, 0.0153],
         [0.8871, 0.3560, 0.1490],
         [0.0464, 0.7582, 0.3031]]])