- microchip
 - 10-6m

- nano scale
    - 2nm @ 2025 
    - 2 x (\(10^{-9}\) m

# What is ML ?

-- its a field of making machines that can think

- AI and not AI
- automation = executing a program with a list of simple instructions
- think and solve problem 
    - iteration
    - a solution -> discard -> next solve -> solve that solves problem
    - adding some knowledge

- heuristics = thinking patterns

- AI tools
    - the more data = better performance
    - will indentify pattern of something
    - alert if your forget
    - 

- reinforcement learning
    - when ever u see the recommendation system . . its AI behind the back

- no knowledge -> knowledge -> decision prediction -> upskill -> job 


# 2 type of class ML
- classification
- regression 

1. typical process 
    - problem scoping

    - data -> 
        - acquisition
        - EDA

    - Split ->
        - Train
        - Test split
            - 80:20 , 70:30

    - modeling ->
        - choose a model
            - linear regression
            - logistic regression
            - decision tree
            - K means 
            - Random forest

    - Training ->
        - Training model ---> model   (model Training)
        - testing ---> model ----> predictions

    - Test ->
        - make prediction on the test
        - compute performance (accuracy & etc)

    - Evaluation ->
        - Testing = test data(give output)  <---->  prediction(give output)

    - improve -> 
        - Try better future, models and parameters

    

# Lets go with a simple examples.

- features 5 - 4 input features - 1 target features
    - < x1,x2,x3,x4 > ----> x (petal2)
    - < y >  ----> y (species)



-----

# saved file


joblib and pickle library

In [ ]:
import joblib
joblib.dump(model, 'linear regression')

-----

# 1. import

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# 2. Data
    - data acquisition (sklearn)
    - EDA (data is clean)
        - visualization (insights)

In [4]:
from sklearn.datasets import load_iris
iris = load_iris()
type(iris)

sklearn.utils._bunch.Bunch

In [5]:
x = iris.data  # x1 , x2 , x3 , x4

y = iris.target     # y

x , y = iris.data , iris.target   # same thing with the top     # features selection

In [6]:
x = pd.DataFrame(x, columns = iris.feature_names)

y = pd.DataFrame(y)

#df_x['species'] = df_y
#df_x


y

0
0    0
1    0
2    0
3    0
4    0
..  ..
145  2
146  2
147  2
148  2
149  2

[150 rows x 1 columns]

In [7]:
df_x.info()
df_x.describe()

NameError: name 'df_x' is not defined

In [ ]:
df_x.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

# Train test split
- train = 80% used for training
- test = 20% used for testing

In [ ]:
train_test_split(x,y)           # kena tgok dulu yg ni bru kita classify ap variables yg sesuai utk dibawah ni

[     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 68                 6.2               2.2                4.5               1.5
 21                 5.1               3.7                1.5               0.4
 35                 5.0               3.2                1.2               0.2
 85                 6.0               3.4                4.5               1.6
 127                6.1               3.0                4.9               1.8
 ..                 ...               ...                ...               ...
 20                 5.4               3.4                1.7               0.2
 32                 5.2               4.1                1.5               0.1
 101                5.8               2.7                5.1               1.9
 95                 5.7               3.0                4.2               1.2
 57                 4.9               2.4                3.3               1.0
 
 [112 rows x 4 columns],
      sepal length (cm)  

In [ ]:
from sklearn.model_selection import train_test_split   

x_train, x_test, y_train , y_test  = train_test_split(x,y)



In [ ]:
#Total 150

len(x_train)    #112    # x1, x2, x3, x4
len(y_train)    #112       #y

len(x_test)     #38        # x1, x2, x3, x4
len(y_test)     #38         #y

38

# modelling

- select modelling - linear regression

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

# Training 
- fit my training data into Linear Regression
- xTrain, yTrain

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

# Test
- own sepal length ....

- rest of the 20% that my model has necer seen before
- try making prediction on that

In [ ]:
model.predict([[2,5,3,4]])

C:\Users\User\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[2.5909577]])

In [ ]:

y_prediction = model.predict(x_test)

In [ ]:
from sklearn.metrics import mean_absolute_error,r2_score

In [ ]:
mean = mean_absolute_error(y_test, y_prediction) # 0.16       #closer it to zero, better the performance
r2 = r2_score(y_test,y_prediction) # 0.93       # farther its from zero, better the performance

mean
r2

0.9308564382311768

### Try train the model

- on 15 data records, check mean_absolute_error
- on 45 data records, check mean_absolute_error
- on 90 data records, check mean_absolute_error
- 


In [ ]:
model.predict([[5.0 , 3.6, 1.4, 0.2]])

C:\Users\User\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[-0.09797352]])

In [ ]:
model.predict([[4.0 , 3.2, 1.1, 0.8]])

C:\Users\User\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[0.29721285]])

In [ ]:
y_prediction.round(2)

array([[ 1.38],
       [ 1.84],
       [-0.09],
       [-0.16],
       [ 0.11],
       [ 2.02],
       [-0.11],
       [ 1.76],
       [ 1.22],
       [ 1.12],
       [-0.04],
       [ 1.15],
       [ 1.81],
       [ 1.75],
       [ 1.98],
       [-0.16],
       [ 0.01],
       [-0.19],
       [ 1.21],
       [-0.04],
       [-0.19],
       [ 2.03],
       [ 1.04],
       [ 1.79],
       [ 1.22],
       [ 1.39],
       [-0.03],
       [ 0.91],
       [-0.11],
       [ 1.83],
       [ 1.46],
       [ 1.26],
       [-0.07],
       [ 1.5 ],
       [ 1.  ],
       [ 1.29],
       [ 1.65],
       [ 1.99]])